### ISSUE TITLE
Move from intree to out of tree

### ISSUE THREAD

**Issue by shahbour** [kubernetes/cloud-provider-vsphere#128]
Hello

I am trying to move vsphere from intree to out of tree but when checking the [docs](https://github.com/kubernetes/cloud-provider-vsphere/tree/master/docs) I see that we can install `deploying_cloud_provider_vsphere_with_rbac.md` and  `deploying_csi_vsphere_with_rbac.md` , what is the differnece between them and should i install them both ?

Thanks

**Comment by shahbour** [comment]
hello

I did try to configure the cloud provider but it did not work. I do have three masters and when starting kubelet with `--cloud-provider=external` it is not tainting it with `node.cloudprovider.kubernetes.io/uninitialized` 

I did made sure it is run with the external flag 

```
/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --cloud-provider=external
```

Checking the log also shows an incorrect username and password. I did double check it .

```
I0115 08:00:27.856728       1 flags.go:27] FLAG: --address="127.0.0.1"
I0115 08:00:27.856869       1 flags.go:27] FLAG: --allocate-node-cidrs="false"
I0115 08:00:27.856894       1 flags.go:27] FLAG: --allow-untagged-cloud="false"
I0115 08:00:27.856926       1 flags.go:27] FLAG: --alsologtostderr="false"
I0115 08:00:27.856946       1 flags.go:27] FLAG: --bind-address="0.0.0.0"
I0115 08:00:27.856963       1 flags.go:27] FLAG: --cert-dir="/var/run/kubernetes"
I0115 08:00:27.856983       1 flags.go:27] FLAG: --cidr-allocator-type="RangeAllocator"
I0115 08:00:27.857000       1 flags.go:27] FLAG: --cloud-config="/etc/cloud/vsphere.conf"
I0115 08:00:27.857017       1 flags.go:27] FLAG: --cloud-provider="vsphere"
I0115 08:00:27.857033       1 flags.go:27] FLAG: --cluster-cidr=""
I0115 08:00:27.857049       1 flags.go:27] FLAG: --cluster-name="kubernetes"
I0115 08:00:27.857065       1 flags.go:27] FLAG: --concurrent-service-syncs="1"
I0115 08:00:27.857095       1 flags.go:27] FLAG: --configure-cloud-routes="true"
I0115 08:00:27.857112       1 flags.go:27] FLAG: --contention-profiling="false"
I0115 08:00:27.857129       1 flags.go:27] FLAG: --controller-start-interval="0s"
I0115 08:00:27.857149       1 flags.go:27] FLAG: --feature-gates=""
I0115 08:00:27.857172       1 flags.go:27] FLAG: --help="false"
I0115 08:00:27.857189       1 flags.go:27] FLAG: --http2-max-streams-per-connection="0"
I0115 08:00:27.857209       1 flags.go:27] FLAG: --kube-api-burst="30"
I0115 08:00:27.857226       1 flags.go:27] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0115 08:00:27.857244       1 flags.go:27] FLAG: --kube-api-qps="20"
I0115 08:00:27.857267       1 flags.go:27] FLAG: --kubeconfig="/etc/kubernetes/controller-manager.conf"
I0115 08:00:27.857285       1 flags.go:27] FLAG: --leader-elect="true"
I0115 08:00:27.857355       1 flags.go:27] FLAG: --leader-elect-lease-duration="15s"
I0115 08:00:27.857374       1 flags.go:27] FLAG: --leader-elect-renew-deadline="10s"
I0115 08:00:27.857395       1 flags.go:27] FLAG: --leader-elect-resource-lock="endpoints"
I0115 08:00:27.857428       1 flags.go:27] FLAG: --leader-elect-retry-period="2s"
I0115 08:00:27.857466       1 flags.go:27] FLAG: --log-backtrace-at=":0"
I0115 08:00:27.857501       1 flags.go:27] FLAG: --log-dir=""
I0115 08:00:27.857528       1 flags.go:27] FLAG: --log-flush-frequency="5s"
I0115 08:00:27.857554       1 flags.go:27] FLAG: --logtostderr="true"
I0115 08:00:27.857580       1 flags.go:27] FLAG: --master=""
I0115 08:00:27.857604       1 flags.go:27] FLAG: --min-resync-period="12h0m0s"
I0115 08:00:27.857632       1 flags.go:27] FLAG: --node-monitor-period="5s"
I0115 08:00:27.857658       1 flags.go:27] FLAG: --node-status-update-frequency="5m0s"
I0115 08:00:27.857685       1 flags.go:27] FLAG: --node-sync-period="0s"
I0115 08:00:27.857710       1 flags.go:27] FLAG: --port="10253"
I0115 08:00:27.857737       1 flags.go:27] FLAG: --profiling="false"
I0115 08:00:27.857763       1 flags.go:27] FLAG: --route-reconciliation-period="10s"
I0115 08:00:27.857788       1 flags.go:27] FLAG: --secure-port="0"
I0115 08:00:27.857813       1 flags.go:27] FLAG: --stderrthreshold="2"
I0115 08:00:27.857838       1 flags.go:27] FLAG: --tls-cert-file=""
I0115 08:00:27.857862       1 flags.go:27] FLAG: --tls-cipher-suites="[]"
I0115 08:00:27.857908       1 flags.go:27] FLAG: --tls-min-version=""
I0115 08:00:27.857934       1 flags.go:27] FLAG: --tls-private-key-file=""
I0115 08:00:27.857959       1 flags.go:27] FLAG: --tls-sni-cert-key="[]"
I0115 08:00:27.857991       1 flags.go:27] FLAG: --use-service-account-credentials="false"
I0115 08:00:27.858016       1 flags.go:27] FLAG: --v="2"
I0115 08:00:27.858041       1 flags.go:27] FLAG: --version="false"
I0115 08:00:27.858076       1 flags.go:27] FLAG: --vmodule=""
W0115 08:00:27.872670       1 authentication.go:55] Authentication is disabled
I0115 08:00:27.872719       1 insecure_serving.go:49] Serving insecurely on 127.0.0.1:10253
I0115 08:00:27.873479       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/cloud-controller-manager...
I0115 08:01:02.905922       1 leaderelection.go:194] successfully acquired lease kube-system/cloud-controller-manager
I0115 08:01:02.907002       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"cloud-controller-manager", UID:"abe9e192-1898-11e9-8648-005056827784", APIVersion:"v1", ResourceVersion:"502252", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' masterfr02_9f09e386-189b-11e9-af9c-005056827ce9 became leader
I0115 08:01:02.907280       1 cloud.go:65] Kubernetes Client Init Succeeded
I0115 08:01:02.907683       1 connectionmanager.go:57] NewConnectionManager with SecretLister
I0115 08:01:02.907812       1 cloud.go:81] API Server is disabled
I0115 08:01:02.909061       1 node_controller.go:89] Sending events to api server.
I0115 08:01:02.911015       1 cloud.go:89] The vSphere cloud provider does not support load balancers
E0115 08:01:02.911063       1 controllermanager.go:240] Failed to start service controller: the cloud provider does not support external load balancers
I0115 08:01:02.911086       1 controllermanager.go:264] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
I0115 08:01:02.911657       1 pvlcontroller.go:107] Starting PersistentVolumeLabelController
I0115 08:01:02.911729       1 controller_utils.go:1025] Waiting for caches to sync for persistent volume label controller
I0115 08:01:02.917224       1 nodemanager.go:134] DiscoverNode nodeID: 420214a4-daf4-494a-f3a1-1ef8193ba968
I0115 08:01:02.918544       1 nodemanager.go:134] DiscoverNode nodeID: 65080242-c105-8f81-ca4a-399d807c7b31
I0115 08:01:02.927758       1 node_controller.go:329] This node enginefr02 is registered without the cloud taint. Will not process.
I0115 08:01:02.927814       1 node_controller.go:329] This node enginefr03 is registered without the cloud taint. Will not process.
I0115 08:01:02.927840       1 node_controller.go:329] This node masterfr01 is registered without the cloud taint. Will not process.
I0115 08:01:02.927864       1 node_controller.go:329] This node masterfr02 is registered without the cloud taint. Will not process.
I0115 08:01:02.927886       1 node_controller.go:329] This node masterfr03 is registered without the cloud taint. Will not process.
I0115 08:01:02.927904       1 node_controller.go:329] This node enginefr01 is registered without the cloud taint. Will not process.
I0115 08:01:03.011966       1 controller_utils.go:1032] Caches are synced for persistent volume label controller
I0115 08:01:06.126425       1 node_controller.go:329] This node masterfr03 is registered without the cloud taint. Will not process.
I0115 08:01:06.405286       1 node_controller.go:329] This node masterfr02 is registered without the cloud taint. Will not process.
I0115 08:01:06.961771       1 node_controller.go:329] This node enginefr01 is registered without the cloud taint. Will not process.
E0115 08:01:08.000278       1 connection.go:63] Failed to create govmomi client. err: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
I0115 08:01:08.000410       1 connectionmanager.go:153] Invalid credentials. Cannot connect to server "192.168.80.121". Fetching credentials from secrets.
E0115 08:01:08.106169       1 datacenter.go:97] Unable to find VM by UUID. VM UUID: 65080242-c105-8f81-ca4a-399d807c7b31
E0115 08:01:08.106216       1 nodemanager.go:241] Error while looking for vm=65080242-c105-8f81-ca4a-399d807c7b31(byUUID) in vc=192.168.80.121 and datacenter=NYDC: No VM found
I0115 08:01:08.106333       1 nodemanager.go:246] Did not find node 65080242-c105-8f81-ca4a-399d807c7b31 in vc=192.168.80.121 and datacenter=NYDC
I0115 08:01:08.106386       1 nodemanager.go:134] DiscoverNode nodeID: 42330242-ac65-178b-7f4b-55fd528de066
E0115 08:01:08.120221       1 datacenter.go:97] Unable to find VM by UUID. VM UUID: 42330242-ac65-178b-7f4b-55fd528de066
E0115 08:01:08.120438       1 nodemanager.go:241] Error while looking for vm=42330242-ac65-178b-7f4b-55fd528de066(byUUID) in vc=192.168.80.121 and datacenter=NYDC: No VM found
I0115 08:01:08.120471       1 nodemanager.go:246] Did not find node 42330242-ac65-178b-7f4b-55fd528de066 in vc=192.168.80.121 and datacenter=NYDC
I0115 08:01:08.120540       1 nodemanager.go:134] DiscoverNode nodeID: 92060242-82cc-7852-1d89-c7bc0bc22bf4
I0115 08:01:08.137954       1 nodemanager.go:280] Found node 420214A4-DAF4-494A-F3A1-1EF8193BA968 as vm=VirtualMachine:vm-1149 in vc=192.168.80.121 and datacenter=NYDC
I0115 08:01:08.138049       1 nodemanager.go:282] Hostname: enginefr01 UUID: 420214a4-daf4-494a-f3a1-1ef8193ba968
I0115 08:01:08.138094       1 instances.go:159] instances.InstanceExistsByProviderID() EXISTS with 420214A4-DAF4-494A-F3A1-1EF8193BA968
I0115 08:01:08.138129       1 nodemanager.go:134] DiscoverNode nodeID: 420214a4-daf4-494a-f3a1-1ef8193ba968
E0115 08:01:08.140675       1 datacenter.go:97] Unable to find VM by UUID. VM UUID: 92060242-82cc-7852-1d89-c7bc0bc22bf4
E0115 08:01:08.140710       1 nodemanager.go:241] Error while looking for vm=92060242-82cc-7852-1d89-c7bc0bc22bf4(byUUID) in vc=192.168.80.121 and datacenter=NYDC: No VM found
I0115 08:01:08.140734       1 nodemanager.go:246] Did not find node 92060242-82cc-7852-1d89-c7bc0bc22bf4 in vc=192.168.80.121 and datacenter=NYDC
I0115 08:01:08.140808       1 nodemanager.go:134] DiscoverNode nodeID: 7b780242-24eb-2ee1-d29b-92da1db0ad5c
E0115 08:01:08.153411       1 datacenter.go:97] Unable to find VM by UUID. VM UUID: 7b780242-24eb-2ee1-d29b-92da1db0ad5c
E0115 08:01:08.153446       1 nodemanager.go:241] Error while looking for vm=7b780242-24eb-2ee1-d29b-92da1db0ad5c(byUUID) in vc=192.168.80.121 and datacenter=NYDC: No VM found
I0115 08:01:08.153470       1 nodemanager.go:246] Did not find node 7b780242-24eb-2ee1-d29b-92da1db0ad5c in vc=192.168.80.121 and datacenter=NYDC
I0115 08:01:08.153510       1 nodemanager.go:134] DiscoverNode nodeID: 4da70242-ccbd-98d4-0d73-4a56f7d3d217
I0115 08:01:08.166091       1 nodemanager.go:280] Found node 420214A4-DAF4-494A-F3A1-1EF8193BA968 as vm=VirtualMachine:vm-1149 in vc=192.168.80.121 and datacenter=NYDC
I0115 08:01:08.166139       1 nodemanager.go:282] Hostname: enginefr01 UUID: 420214a4-daf4-494a-f3a1-1ef8193ba968
I0115 08:01:08.166173       1 instances.go:84] instances.NodeAddressesByProviderID() FOUND with 420214A4-DAF4-494A-F3A1-1EF8193BA968
E0115 08:01:08.166447       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:522
/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513
/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:82
/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/signal_unix.go:390
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphere/instances.go:85
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:468
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:167
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:145
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:124
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x182173e]

goroutine 84 [running]:
k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1af5cc0, 0x37769b0)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513 +0x1b9
k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphere.(*instances).NodeAddressesByProviderID(0xc00000cdd0, 0x215c820, 0xc000092038, 0xc0007d6db0, 0x2e, 0xc000092038, 0xc0007d6db0, 0x2e, 0xc00070d101, 0x0)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphere/instances.go:85 +0x3be
k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud.getNodeAddressesByProviderIDOrName(0x216a720, 0xc00000cdd0, 0xc00015f000, 0x1, 0x0, 0x0, 0xc0006f1a00, 0xc00083dda8)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:468 +0x81
k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeController).updateNodeAddress(0xc0000ab7c0, 0xc00015f000, 0x216a720, 0xc00000cdd0)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:167 +0x13e
k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeController).UpdateNodeStatus(0xc0000ab7c0)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:145 +0x15c
k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeController).UpdateNodeStatus-fm()
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:124 +0x2a
k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006f1c40)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006f1c40, 0x45d964b800, 0x0, 0x1, 0xc0004f3980)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0006f1c40, 0x45d964b800, 0xc0004f3980)
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeController).Run
	/home/travis/gopath/src/k8s.io/cloud-provider-vsphere/vendor/k8s.io/kubernetes/pkg/controller/cloud/node_controller.go:124 +0xb7
```

**Comment by dvonthenen** [comment]
Hi @shahbour 

I noticed that behavior as well while recently testing the CCM's zone support. The PR https://github.com/kubernetes/cloud-provider-vsphere/pull/130 is currently pending (to be merged real soon), but I have updated the documentation to that effect. The code that is supposed to set the taint when setting to external lives in k/k and not apart of the CCM. For now, there is at least a workaround to get you going.

**Comment by dvonthenen** [comment]
Just for some validation, I rebooted a node with the cloud provider set to `external`, I totally would have thought the node (effectively simulating a crash/restart) would taint on start up... but it doesn't.

Recommend manually tainting as in the docs. A bug can be filed in the k/k repo. I think we can close this since we don't own the code that is suppose to make that process happen.
